#!/bin/bash

# Display listening ports, PID and name of the program to which each socket belongs

echo "Listening ports:"
netstat -tulpn | awk '{print $4,$7}' | grep LISTEN
echo ""
echo "PID and name of the program to which each socket belongs:"
netstat -tulpn | awk '{print $4,$7}' | grep LISTEN | awk -F\/ '{print $2,$1}'
